theme: minima
title: KD's Programming Voyage
author: kadowning1
email: kadowning1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Excited to start a web development bootcamp to enhance my skills and become a Dev!  I know it will be a voyage of headache, lack of sleep, and pressure, but eagar to build each and every day.

# social links
twitter_username: kadowning # DO NOT include the @ character, or else the build will fail!
github_username:  kadowning1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
